[package]
name = "ape"
version = "0.1.2"

description = "A library for reading and writing APEv2 tags"
keywords = ["ape"]
authors = ["Kilte Leichnam <nwotnbm@gmail.com>"]

homepage = "http://rust-ape.leichnam.rip"
documentation = "http://rust-ape.leichnam.rip"
repository = "https://github.com/Kilte/rust-ape"

readme = "README.md"
license = "MIT"

exclude = ["data/*"]

[dependencies]
byteorder = "1.0.0"
